FROM alpine:3.13
RUN PICARD_VER="2.25.2" && \
    set -x && \
    apk update && \
    apk add --no-cache --virtual .tmp1 git ca-certificates wget && \
    apk add --no-cache R bash openjdk11-jre-headless libc6-compat zlib-dev && \
    ln -s /lib/libc.musl-x86_64.so.1 /lib/ld-linux-x86-64.so.2 && \
    cd /tmp && \
    wget https://github.com/broadinstitute/picard/releases/download/${PICARD_VER}/picard.jar && \
    mv picard.jar /usr/local/bin/ && \
    chmod +x /usr/local/bin/picard.jar && \
    apk del .tmp1
CMD ["/bin/bash"]
